### PR TITLE
Fix bug in Axios urls

### LINKED ISSUE #36: Fix bug in connecting to prod server
## Current Behavior

CORS issue "redirect is not allowed for a preflight request."
and not handling default port.

## Expected Behavior

Webapp should connect to public server handling both https and http, and no specified port

### PR DESCRIPTION
**Pull request by AlZorba**
**Issue** :  `https://github.com/archaiodata/thacer/issues/36`

**Description** :    
This PR fix bug in prod environment by allowing https and default port. It also clean inline CSS in header component.

### CODE REVIEW

File: src/services/ApiClient.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export function fetchAllTrenches() {
   return axios({
     headers: { "Content-Type": "application/x-www-form-urlencoded" },
     method: "get",
-    url: `//${server}:9000/idig/${project}/trenches`,
```
Comment (francoiscrouzet) [inline src/services/ApiClient.js:37]: @AlZorba This mean the user must always add `:9000` in the input ?

File: src/components/HeaderIdig.vue [hunk 2]
```diff
@@ -150,4 +145,9 @@ export default {
   background-color: #28a745;
   border-color: #28a745;
 }
+.input-header {
+  background: #212529;
+  border: 0px;
+  width: 6em;
+}
```
Comment (francoiscrouzet) [inline src/components/HeaderIdig.vue:152]: @AlZorba We both forgot to change the `<style>` to `<style scoped>`
If you do some other change on this PR, you can do this too. Otherwise another time is fine

**Review by francoiscrouzet — COMMENTED** [review]
@AlZorba Not sure about this `:9000` removal. Is it on purpose ? If yes, you can merge.
If not, you can correct it, and may also correct the `style scoped` thing

File: src/services/ApiClient.js (hunk 1 above)
Comment (AlZorba) [reply src/services/ApiClient.js:37]: yes whenhis server got port 9000 but on public server we should be able to point to default.
