### PR TITLE
Fix eslint errors and warnings

### LINKED ISSUE #22: Fix remaining eslint errors and warnings
## What we want

When running `npm run lint`, we should have no errors or warnings.

## Why we want it

To have a clear console easy to read to not miss important warnings

### PR DESCRIPTION
**Pull request by AlZorba**
**Issue** :  `https://github.com/esag-swiss/iDig-Webapp/issues/22`

**Description** :    
This PR fixes multiple eslint errors mainly css inline and wrong default type in props

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -95,9 +95,13 @@ export default {
   },
   computed: {
     selectedData() {
-      return this.trenchData?.filter((object) => {
-        return object.Type.includes(this.selectedFilter);
-      });
+      if (this.trenchData) {
+        return this.trenchData?.filter((object) => {
```
Comment (francoiscrouzet) [inline src/App.vue]: @AlZorba optional : the question mark is not necessary I think. (that's the smallest dead code which can exist : 1 character !)

File: src/App.vue [hunk 2]
```diff
@@ -95,9 +95,13 @@ export default {
...
+          return object.Type.includes(this.selectedFilter);
+        });
+      } else {
+        return {};
+      }
```
Comment (francoiscrouzet) [inline src/App.vue:104]: @AlZorba side note, the whole function could be rewritten with the `??`. I would personnaly not use it in this case, I find it very difficult to read
```
return this.trenchData?.filter((object) => {
        return object.Type.includes(this.selectedFilter)
} ?? {}
```

"Javascript double question mark is a logical operator that takes two values and returns the right-hand value if the left-hand value is undefined or null, Else returns the left-hand operand."

File: src/components/TheTable.vue [hunk 3]
```diff
@@ -1,16 +1,11 @@
 <template>
   <div v-show="TheItem" class="TheItemframe" @click="removeLTheItem()"></div>
   <TheItem
-    v-show="TheItem"
+    v-if="TheItem"
```
Comment (francoiscrouzet) [inline src/components/TheTable.vue]: @AlZorba I don't understand this one. It is testing that the component TheItem is defined ? I think I've read something like that in the doc. What is the intent ?

File: src/components/TheTable.vue [hunk 4]
```diff
@@ -1,16 +1,11 @@
...
     :selectedType="selectedType"
     :selectedRow="selectedRow"
   >
   </TheItem>
-  <!-- old search method -->
-  <!-- <input class="m-2" v-model="searchTerm" /> -->
-
-  <!-- Work in progress bouton pour afficher les images des attachments -->
-  <!-- <button type="button" @click="getImage">Image</button> -->
```
Comment (francoiscrouzet) [inline src/components/TheTable.vue:13]: 👍

**Comment by francoiscrouzet** [comment]
@AlZorba when running `npm run lint`, there is still one last issue : 
```
/Users/dev/code/archaiodata/iDig-Webapp/src/components/TheItem.vue
  49:18  warning  Variable 'field' is already declared in the upper scope  vue/no-template-shadow
```

**Review by francoiscrouzet — COMMENTED** [review]
@AlZorba
It's super, it closes several issues and is very clean, cool !
- todo : check this strange thing with v-if="TheItem", 
- 2 optional things : the `?`, and one remaining eslint error which may be done later

File: src/components/TheTable.vue (hunk 3 above)
Comment (AlZorba) [reply src/components/TheTable.vue]: I should have name the boolean a different name than the component. When v-show the component is created but not show, when v-if not created. It is needed here because otherwise component is created with missing props.

File: src/components/TheTable.vue (hunk 4 above)
Comment (AlZorba) [reply src/components/TheTable.vue:13]: yes i know :)

File: src/App.vue (hunk 2 above)
Comment (AlZorba) [reply src/App.vue:104]: Fancy !

File: src/components/TheTable.vue (hunk 3 above)
Comment (francoiscrouzet) [reply src/components/TheTable.vue]: @AlZorba ah ok ! For me this definitely need to be changed. The name should reflect what it contains, in camelCase, and also you have 2 variables with the same name, it's a miracle that it works :D

File: src/App.vue (hunk 1 above)
Comment (AlZorba) [reply src/App.vue]: ok
